### ISSUE TITLE
Winner

### ISSUE THREAD

**Issue by nericode** [happones/nativescript-conekta#1]
Revise que ya tienes el plugin con ios, voy a dar de baja el mio para que ya puedas cargar el tuyo en el marketplace, esto es genial...

:+1:

**Comment by happones** [comment]
Claro, aun asi ya lo publique como [nativescript-conekta-sdk](https://www.npmjs.com/package/nativescript-conekta-sdk)

**Comment by nericode** [comment]
Vale, que gran aportación.

**Comment by nericode** [comment]
Te contacto por aquí, oye no nos quieres ayudar a colaborar en el plugin de marcadopago ya tenemos la parte de Android.

**Comment by happones** [comment]
Te late si nos comunicamos por el canal de slack de Nativescript, te mande mensaje
