### ISSUE TITLE
Integración con Ionic 3

### ISSUE THREAD

**Issue by maniatikorn** [happones/nativescript-conekta#2]
Hola, disculpa que abra un issue para preguntar.

Intenté usar este proyecto para un app en ionic 3 con typescript, pero fallé.

Es factible que siga intentando integrarlo? estoy un poco perdido.

Gracias

**Comment by happones** [comment]
Hola que tal este plugin solo funciona no [Nativescript](https://www.nativescript.org/), pero con Ionic de acuerdo como funciona puedes integrar la libreria de [JS](https://developers.conekta.com/libraries/javascript) que tiene Conekta, no deberás tener ningún problema.

**Comment by maniatikorn** [comment]
Muy bien, muchas gracias @happones !
