### ISSUE TITLE
Alternativa para validaciones

### ISSUE THREAD

**Issue by cesarureno** [happones/nativescript-conekta#3]
Hola @happones antes que nada muchas gracias por tu plugin nos ha sido de gran ayuda. Y ahora vengo con una duda, en la librería de JS en su documentación dice que tiene validaciones, pero veo que para los SDK de iOS y android no lo tienen. Cual seria la forma correcta de validar las tarjetas?
Saludos.

**Comment by nericode** [comment]
Como estas @cesarureno, yo actualmente valido mis tarjetas con el siguiente plugin https://www.npmjs.com/package/card-validator, espero que te funcione también a ti.

**Comment by cesarureno** [comment]
Muchas gracias @NeriCodec le dare una revisada
